# Generated by Django 4.1.7 on 2023-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbox', '0002_answer_question_startracker_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_answers',
            field=models.ManyToManyField(related_name='users', to='questionbox.answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_questions',
            field=models.ManyToManyField(related_name='users', to='questionbox.question'),
        ),
    ]
