# Generated by Django 4.1.7 on 2023-03-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbox', '0003_user_fav_answers_user_fav_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='questionbox.answer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='questionbox.question'),
        ),
    ]
