# Generated by Django 4.1.7 on 2023-03-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbox', '0007_remove_question_accepted_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
