# Generated by Django 4.1.7 on 2023-03-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbox', '0008_answer_is_accepted'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('text', 'author', 'question'), name='answer_constraints'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('text', 'author'), name='question_constraints'),
        ),
    ]
