# Generated by Django 4.1.7 on 2023-04-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbox', '0010_alter_answer_author_alter_question_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StarTracker',
        ),
    ]
