# Generated by Django 4.2 on 2023-04-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbox', '0011_delete_startracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='fav_users', to='questionbox.answer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='fav_users', to='questionbox.question'),
        ),
    ]
