# Generated by Django 4.2 on 2023-04-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbox', '0012_alter_user_fav_answers_alter_user_fav_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='questionbox.answer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='questionbox.question'),
        ),
    ]
